version: '3.8'
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aegis_db
    ports:
      - "5432:5432"

  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/aegis_db
    depends_on:
      - db

  dashboard:
    build: ./frontend
    ports:
      - "3000:3000"